-- P3-T074: positive/negative RLS coverage.
-- Designed for staging/local with pgTAP installed.
-- Tests policy predicates and grant boundaries; no production data is required.

begin;
select plan(18);

select ok((select count(*) = 17 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and c.relname in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows') and c.relrowsecurity), 'all 17 application tables have RLS enabled');
select ok((select count(*) = 17 from pg_policies where schemaname='public' and tablename in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows') and cmd='SELECT'), 'all application tables have SELECT policy coverage');
select ok((select count(*) = 11 from pg_policies where schemaname='public' and tablename in ('customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','invoice_records') and cmd='SELECT' and qual like '%app_role() = ANY (ARRAY[''sales''::text, ''operations''::text, ''admin''::text])%'), 'positive: operational SELECT policy covers sales/operations/admin');
select ok((select count(*) = 1 from pg_policies where schemaname='public' and tablename='profiles' and policyname='profiles_self_select' and cmd='SELECT' and qual like '%id = auth.uid()%'), 'positive: profiles are restricted to the caller identity');
select ok((select count(*) = 1 from pg_policies where schemaname='public' and tablename='financial_adjustments' and policyname='financial_adjustments_admin_select' and cmd='SELECT' and qual like '%app_role() = ''admin''%'), 'positive: financial adjustments are Admin-read-only');
select ok((select count(*) = 1 from pg_policies where schemaname='public' and tablename='audit_logs' and policyname='audit_logs_admin_select' and cmd='SELECT' and qual like '%app_role() = ''admin''%'), 'positive: audit logs are Admin-read-only');
select ok((select count(*) = 1 from pg_policies where schemaname='public' and tablename='import_batches' and policyname='import_batches_admin_select' and cmd='SELECT' and qual like '%app_role() = ''admin''%'), 'positive: import batches are Admin-read-only');
select ok((select count(*) = 1 from pg_policies where schemaname='public' and tablename='import_rows' and policyname='import_rows_admin_select' and cmd='SELECT' and qual like '%app_role() = ''admin''%'), 'positive: import rows are Admin-read-only');
select ok((select count(*) = 0 from pg_policies where schemaname='public' and tablename in ('financial_adjustments','audit_logs','import_batches','import_rows') and qual like '%app_role() = ANY (ARRAY[''sales''::text, ''operations''::text, ''admin''::text])%'), 'negative: admin-only tables do not expose operational-role predicate');
select ok((select count(*) = 0 from pg_policies where schemaname='public' and tablename in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows') and cmd in ('INSERT','UPDATE','DELETE')), 'negative: direct write RLS policies are absent');
select ok((select has_table_privilege('anon','public.orders','select') = false), 'negative: anon cannot SELECT orders');
select ok((select has_table_privilege('authenticated','public.orders','insert') = false and has_table_privilege('authenticated','public.orders','update') = false and has_table_privilege('authenticated','public.orders','delete') = false), 'negative: authenticated cannot directly write orders');
select ok((select has_table_privilege('authenticated','public.orders','select') = true), 'positive: authenticated retains SELECT orders');
select ok((select count(*) = 17 from information_schema.role_table_grants where grantee='authenticated' and table_schema='public' and privilege_type='SELECT' and table_name in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows')), 'positive: authenticated SELECT grants cover all application tables');
select ok((select count(*) = 0 from information_schema.role_table_grants where grantee='authenticated' and table_schema='public' and privilege_type in ('INSERT','UPDATE','DELETE') and table_name in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows')), 'negative: authenticated direct writes are not granted');
select ok((select count(*) = 0 from information_schema.role_table_grants where grantee='anon' and table_schema='public' and privilege_type in ('SELECT','INSERT','UPDATE','DELETE') and table_name in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows')), 'negative: anon has no application-table grants');
select ok((select count(*) = 0 from pg_policies where schemaname='public' and tablename in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows') and roles = '{public}'), 'negative: no PUBLIC-role policies exist');
select ok((select count(*) = 4 from pg_policies where schemaname='public' and tablename in ('financial_adjustments','audit_logs','import_batches','import_rows') and cmd='SELECT'), 'negative: sensitive tables have exactly one SELECT policy each');
select ok((select count(*) = 17 from pg_policies where schemaname='public' and tablename in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows') and cmd='SELECT'), 'RLS matrix remains exactly one SELECT policy per application table');

select * from finish();
rollback;
