-- P3-T077 / P5-T090 / P5-T091 / P5-T096 / P5-T097 / P5-T098 / P5-T099 / P7-T113 / P7-T116 / P7-T118 / P7-T119 / P7-T124 / P8-T128 / P8-T129 / P8-T132 / P9-T138 rebuild verification.
begin;
select plan(18);

select ok((select count(*) >= 49 from supabase_migrations.schema_migrations) and (select count(*) = 1 from supabase_migrations.schema_migrations where version='20260915090000'), 'rebuild applied the complete repository migration chain including T138');
select ok((select count(*) = 20 from information_schema.tables where table_schema='public' and table_type='BASE TABLE' and table_name in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','invoice_template_versions','invoice_print_events','order_events','audit_logs','import_batches','import_rows','command_idempotency')), 'all 20 application/foundation tables exist');
select ok((select count(*) = 3 from information_schema.sequences where sequence_schema='public' and sequence_name in ('customer_code_seq','order_number_seq','parcel_number_seq')), 'all 3 identifier sequences exist');
select ok((select count(*) = 19 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and c.relrowsecurity and c.relname in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','invoice_template_versions','invoice_print_events','order_events','audit_logs','import_batches','import_rows')), 'all 19 application tables retain RLS');
select ok((select count(*) = 1 from pg_policies where schemaname='public' and tablename='invoice_print_events' and policyname='invoice_print_events_authenticated_select' and cmd='SELECT'), 'invoice print event SELECT policy exists');
select ok((select count(*) = 15 from (select p.proname, pg_get_function_identity_arguments(p.oid) args from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public'] and p.proname in ('app_role','create_order','update_order','confirm_order','cancel_order','cancel_parcel','create_parcel','allocate_parcel_item','allocate_parcel_items','claim_command_idempotency','complete_command_idempotency','resolve_customer_by_phone','record_invoice_print','capture_invoice_historical_snapshot','assign_parcel_shipper')) approved), 'all 15 approved SECURITY DEFINER application functions pin search_path');
select ok((select count(*) = 1 from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname = 'create_profile' and p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public, auth']), 'create_profile is SECURITY DEFINER with its controlled auth search_path');
select ok((select count(*) = 1 from pg_proc p where p.pronamespace = 'public'::regnamespace and p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public'] and p.proname = 'set_profile_active'), 'set_profile_active is SECURITY DEFINER with controlled search_path');
select ok((select has_function_privilege('authenticated','public.set_profile_active(uuid,boolean)','execute') and has_function_privilege('anon','public.set_profile_active(uuid,boolean)','execute') = false and has_function_privilege('authenticated','public.create_profile(uuid,text,text)','execute') and has_function_privilege('anon','public.create_profile(uuid,text,text)','execute') = false), 'profile administration commands retain least privilege');
select ok((select count(*) = 1 from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname = 'normalize_uae_phone' and not p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public']), 'UAE phone normalization function exists with controlled search_path');
select ok((select count(*) = 1 from information_schema.table_constraints where constraint_schema='public' and table_name='invoice_records' and constraint_name='invoice_records_template_version_fkey' and constraint_type='FOREIGN KEY'), 'invoice records reference controlled template versions');
select ok((select count(*) = 1 from information_schema.columns where table_schema='public' and table_name='invoice_records' and column_name='source_snapshot' and is_nullable='NO' and data_type='jsonb'), 'invoice records retain a mandatory historical source snapshot');
select ok((select count(*) = 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='invoice_template_versions' and t.tgname='trg_invoice_template_versions_immutable' and not t.tgisinternal), 'invoice template versions have immutable lineage enforcement');
select ok((select count(*) = 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='invoice_print_events' and t.tgname='trg_invoice_print_events_immutable' and not t.tgisinternal), 'invoice print events have immutable audit enforcement');
select ok((select count(*) = 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='invoice_records' and t.tgname='trg_invoice_record_historical_snapshot_immutable' and not t.tgisinternal), 'invoice historical snapshots have immutable update enforcement');
select ok((select count(*) = 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='invoice_records' and t.tgname='trg_invoice_records_capture_historical_snapshot' and not t.tgisinternal), 'new invoice records capture historical snapshots at generation');
select ok((select count(*) = 1 from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname = 'prevent_invoice_record_historical_snapshot_mutation' and not p.prosecdef), 'historical snapshot mutation guard is not exposed as a privileged command');
select ok((select count(*) = 1 from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname = 'assign_parcel_shipper'), 'T138 shipper assignment command is present');
select * from finish();
rollback;
