-- P3-T077 / P5-T090 / P5-T091 / P5-T096 / P5-T097 / P5-T098 / P5-T099 / P7-T113 / P7-T116 / P7-T118 rebuild verification.
begin;
select plan(10);

select ok((select count(*) = 43 from supabase_migrations.schema_migrations), 'rebuild applied the complete repository migration chain');
select ok((select count(*) = 18 from information_schema.tables where table_schema='public' and table_type='BASE TABLE' and table_name in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows','command_idempotency')), 'all 18 application/foundation tables exist');
select ok((select count(*) = 3 from information_schema.sequences where sequence_schema='public' and sequence_name in ('customer_code_seq','order_number_seq','parcel_number_seq')), 'all 3 identifier sequences exist');
select ok((select count(*) = 17 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and c.relrowsecurity and c.relname in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows')), 'all 17 application tables retain RLS');
select ok((select count(*) = 18 from pg_policies where schemaname='public' and tablename in ('profiles','customers','shippers','orders','order_items','parcels','parcel_items','delivery_outcomes','cod_obligations','cod_obligation_allocations','cod_receipts','financial_adjustments','invoice_records','order_events','audit_logs','import_batches','import_rows') and cmd='SELECT'), 'all application SELECT policies exist including admin profile control');
select ok((select count(*) = 12 from (select p.proname, pg_get_function_identity_arguments(p.oid) args from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public'] and p.proname in ('app_role','create_order','update_order','confirm_order','cancel_order','cancel_parcel','create_parcel','allocate_parcel_item','allocate_parcel_items','claim_command_idempotency','complete_command_idempotency','resolve_customer_by_phone')) approved), 'all 12 approved SECURITY DEFINER application functions pin search_path');
select ok((select count(*) = 1 from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname = 'create_profile' and p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public, auth']), 'create_profile is SECURITY DEFINER with its controlled auth search_path');
select ok((select count(*) = 1 from pg_proc p where p.pronamespace = 'public'::regnamespace and p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public'] and p.proname = 'set_profile_active'), 'set_profile_active is SECURITY DEFINER with its controlled search_path');
select ok((select has_function_privilege('authenticated','public.set_profile_active(uuid,boolean)','execute') and has_function_privilege('anon','public.set_profile_active(uuid,boolean)','execute') = false and has_function_privilege('authenticated','public.create_profile(uuid,text,text)','execute') and has_function_privilege('anon','public.create_profile(uuid,text,text)','execute') = false), 'profile administration commands retain least privilege');
select ok((select count(*) = 1 from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname = 'normalize_uae_phone' and not p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public']), 'UAE phone normalization function exists with controlled search_path');
select * from finish();
rollback;
