begin;

select plan(16);

select ok((select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel' and pg_get_function_identity_arguments(p.oid)='p_parcel_id uuid, p_tracking_id text, p_idempotency_key text'),'dispatch_parcel command exists');
select ok((select p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch command pins search_path');
select ok((select has_function_privilege('anon','public.dispatch_parcel(uuid,text,text)','execute')=false and has_function_privilege('authenticated','public.dispatch_parcel(uuid,text,text)','execute')=true),'dispatch command is browser-role restricted');
select ok((select pg_get_functiondef(p.oid) like '%app_role() not in (''operations'',''admin'')%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch requires operations/admin');
select ok((select pg_get_functiondef(p.oid) like '%v_state<>''Prepared''%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch is restricted to Prepared parcels');
select ok((select pg_get_functiondef(p.oid) like '%where p.id=p_parcel_id%for update%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'parcel row is locked before dispatch');
select ok((select pg_get_functiondef(p.oid) like '%v_shipper_id is null%' and pg_get_functiondef(p.oid) like '%Assigned shipper is not active%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch validates assigned active shipper');
select ok((select pg_get_functiondef(p.oid) like '%validate_unique_tracking_id%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch invokes server-side tracking validation');
select ok((select pg_get_functiondef(p.oid) like '%tracking_id=btrim(p_tracking_id)%' and pg_get_functiondef(p.oid) like '%normalized_tracking_id=v_normalized_tracking_id%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch stores canonical tracking ID');
select ok((select pg_get_functiondef(p.oid) like '%state=''Dispatched''%' and pg_get_functiondef(p.oid) like '%dispatch_at=v_dispatch_at%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch updates authoritative parcel state and timestamp');
select ok((select pg_get_functiondef(p.oid) like '%Dispatched%' and pg_get_functiondef(p.oid) like '%insert into public.order_events%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch emits immutable order event');
select ok((select pg_get_functiondef(p.oid) like '%insert into public.audit_logs%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch emits audit record');
select ok((select pg_get_functiondef(p.oid) like '%claim_command_idempotency(''dispatch_parcel''%' and pg_get_functiondef(p.oid) like '%complete_command_idempotency(''dispatch_parcel''%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch is idempotent and retry safe');
select ok((select pg_get_functiondef(p.oid) like '%Parcel not found%' and pg_get_functiondef(p.oid) like '%Only Prepared parcels can be dispatched%' and pg_get_functiondef(p.oid) like '%Tracking ID is required%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch has explicit validation errors');
select ok((select pg_get_functiondef(p.oid) like '%jsonb_build_object(''parcel_number''%' and pg_get_functiondef(p.oid) like '%tracking_id%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch event/audit metadata includes parcel and tracking context');
select ok((select exists (select 1 from pg_indexes where schemaname='public' and indexname='idx_parcels_normalized_tracking_id_unique')),'global normalized tracking uniqueness index exists');
select ok((select pg_get_functiondef(p.oid) like '%state=''Dispatched''%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dispatch_parcel'),'dispatch has explicit Dispatched transition');

select * from finish();
rollback;
