begin;

select plan(15);

select ok((select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome' and pg_get_function_identity_arguments(p.oid)='p_parcel_id uuid, p_outcome text, p_note text, p_idempotency_key text'),'delivery outcome command exists');
select ok((select p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'delivery outcome command pins search_path');
select ok((select has_function_privilege('anon','public.record_delivery_outcome(uuid,text,text,text)','execute')=false and has_function_privilege('authenticated','public.record_delivery_outcome(uuid,text,text,text)','execute')=true),'delivery outcome command is browser-role restricted');
select ok((select pg_get_functiondef(p.oid) like '%app_role() not in (''operations'',''admin'')%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'delivery outcome requires operations/admin');
select ok((select pg_get_functiondef(p.oid) like '%p_outcome%in%(''Delivered'',''RTO'',''Lost'',''Damaged'',''NDR'')%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'delivery outcome validates supported outcomes');
select ok((select pg_get_functiondef(p.oid) like '%p_parcel_id%is null%' and pg_get_functiondef(p.oid) like '%p_idempotency_key%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'delivery outcome validates required inputs');
select ok((select pg_get_functiondef(p.oid) like '%where p.id=p_parcel_id%for update%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'parcel row is locked before outcome mutation');
select ok((select pg_get_functiondef(p.oid) like '%Only In Transit parcels can receive a delivery outcome%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'baseline outcome transition requires In Transit');
select ok((select pg_get_functiondef(p.oid) like '%update public.parcels%' and pg_get_functiondef(p.oid) like '%set state=btrim(p_outcome)%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'outcome updates authoritative parcel state');
select ok((select pg_get_functiondef(p.oid) like '%insert into public.delivery_outcomes%' and pg_get_functiondef(p.oid) like '%performed_by%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'outcome creates immutable delivery outcome record');
select ok((select pg_get_functiondef(p.oid) like '%insert into public.order_events%' and pg_get_functiondef(p.oid) like '%previous_state%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'outcome emits domain event with transition context');
select ok((select pg_get_functiondef(p.oid) like '%insert into public.audit_logs%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'outcome emits audit record');
select ok((select pg_get_functiondef(p.oid) like '%claim_command_idempotency(''record_delivery_outcome''%' and pg_get_functiondef(p.oid) like '%complete_command_idempotency(''record_delivery_outcome''%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'delivery outcome command is idempotent and retry safe');
select ok((select pg_get_functiondef(p.oid) like '%rto_at=case when btrim(p_outcome)=''RTO''%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'RTO records the parcel RTO timestamp');
select ok((select pg_get_functiondef(p.oid) like '%Parcel not found%' and pg_get_functiondef(p.oid) like '%Delivery outcome must be%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_delivery_outcome'),'delivery outcome has explicit validation errors');

select * from finish();
rollback;
