-- P11-T168: parcel expected COD allocation contract.
begin;

select plan(10);

select ok((select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='allocate_cod_obligation_to_parcel' and pg_get_function_identity_arguments(p.oid)='p_cod_obligation_id uuid, p_parcel_id uuid, p_expected_amount numeric, p_idempotency_key text'),'parcel COD allocation command exists');
select ok((select p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='allocate_cod_obligation_to_parcel'),'parcel COD allocation retains SECURITY DEFINER boundary');
select ok((select pg_get_functiondef(p.oid) like '%public.app_role() not in (''sales'',''operations'',''admin'')%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='allocate_cod_obligation_to_parcel'),'parcel COD allocation requires an authenticated operational role');
select ok((select position('claim_command_idempotency' in pg_get_functiondef(p.oid)) > 0 and position('complete_command_idempotency' in pg_get_functiondef(p.oid)) > 0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='allocate_cod_obligation_to_parcel'),'parcel COD allocation is idempotent and retry safe');
select ok((select pg_get_functiondef(p.oid) like '%from public.cod_obligations%' and pg_get_functiondef(p.oid) like '%where id = p_cod_obligation_id%' and pg_get_functiondef(p.oid) like '%for update%' and pg_get_functiondef(p.oid) like '%from public.parcels%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='allocate_cod_obligation_to_parcel'),'allocation locks the authoritative obligation and parcel');
select ok((select pg_get_functiondef(p.oid) like '%v_parcel.order_id <> v_obligation.order_id%' and pg_get_functiondef(p.oid) like '%v_parcel.state = ''Cancelled''%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='allocate_cod_obligation_to_parcel'),'allocation validates parcel ownership and rejects cancelled parcels');
select ok((select pg_get_functiondef(p.oid) like '%insert into public.cod_obligation_allocations(cod_obligation_id, parcel_id, expected_amount)%' and pg_get_functiondef(p.oid) like '%p_expected_amount%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='allocate_cod_obligation_to_parcel'),'allocation stores the explicit non-negative expected amount');
select ok((select pg_get_functiondef(p.oid) like '%CodObligationAllocatedToParcel%' and pg_get_functiondef(p.oid) like '%insert into public.audit_logs%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='allocate_cod_obligation_to_parcel'),'allocation records domain and audit evidence');
select ok((select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a join pg_roles r on r.oid=a.grantee where n.nspname='public' and p.proname='allocate_cod_obligation_to_parcel' and pg_get_function_identity_arguments(p.oid)='p_cod_obligation_id uuid, p_parcel_id uuid, p_expected_amount numeric, p_idempotency_key text' and r.rolname='authenticated' and a.privilege_type='EXECUTE') and not exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a join pg_roles r on r.oid=a.grantee where n.nspname='public' and p.proname='allocate_cod_obligation_to_parcel' and pg_get_function_identity_arguments(p.oid)='p_cod_obligation_id uuid, p_parcel_id uuid, p_expected_amount numeric, p_idempotency_key text' and r.rolname='anon' and a.privilege_type='EXECUTE')),'parcel COD allocation command remains restricted to authenticated browser role');
select ok((select position('cod_obligation_id, parcel_id' in pg_get_constraintdef(c.oid)) > 0 from pg_constraint c join pg_class cl on cl.oid=c.conrelid join pg_namespace cn on cn.oid=cl.relnamespace where cn.nspname='public' and cl.relname='cod_obligation_allocations' and c.contype='u'),'one allocation per obligation and parcel is enforced by the database');

select * from finish();
rollback;
