-- P11-T171: COD receipt entry contract.
begin;

select plan(10);

select ok((select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_cod_receipt' and pg_get_function_identity_arguments(p.oid)='p_cod_obligation_id uuid, p_parcel_id uuid, p_received_amount numeric, p_idempotency_key text'),'COD receipt entry command exists');
select ok((select p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_cod_receipt'),'COD receipt command retains SECURITY DEFINER boundary');
select ok((select pg_get_functiondef(p.oid) like '%public.app_role() not in (''sales'',''operations'',''admin'')%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_cod_receipt'),'COD receipt command requires an authenticated operational role');
select ok((select position('claim_command_idempotency' in pg_get_functiondef(p.oid)) > 0 and position('complete_command_idempotency' in pg_get_functiondef(p.oid)) > 0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_cod_receipt'),'COD receipt entry is idempotent and retry safe');
select ok((select pg_get_functiondef(p.oid) like '%from public.cod_obligations%' and pg_get_functiondef(p.oid) like '%where id = p_cod_obligation_id%' and pg_get_functiondef(p.oid) like '%for update%' and pg_get_functiondef(p.oid) like '%from public.parcels%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_cod_receipt'),'receipt entry locks the authoritative obligation and parcel');
select ok((select pg_get_functiondef(p.oid) like '%v_parcel.order_id <> v_obligation.order_id%' and pg_get_functiondef(p.oid) like '%v_parcel.state = ''Cancelled''%' and pg_get_functiondef(p.oid) like '%v_obligation.state in (''Voided'',''Closed'')%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_cod_receipt'),'receipt entry validates obligation state, parcel ownership and cancellation');
select ok((select pg_get_functiondef(p.oid) like '%insert into public.cod_receipts(%' and pg_get_functiondef(p.oid) like '%v_allocation.expected_amount%' and pg_get_functiondef(p.oid) like '%p_received_amount%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_cod_receipt'),'receipt entry stores expected snapshot and received amount');
select ok((select pg_get_functiondef(p.oid) like '%CodReceiptRecorded%' and pg_get_functiondef(p.oid) like '%insert into public.audit_logs%' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='record_cod_receipt'),'receipt entry records domain and audit evidence');
select ok((select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a join pg_roles r on r.oid=a.grantee where n.nspname='public' and p.proname='record_cod_receipt' and pg_get_function_identity_arguments(p.oid)='p_cod_obligation_id uuid, p_parcel_id uuid, p_expected_amount_snapshot numeric, p_received_amount numeric, p_idempotency_key text' and r.rolname='authenticated' and a.privilege_type='EXECUTE') and not exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a join pg_roles r on r.oid=a.grantee where n.nspname='public' and p.proname='record_cod_receipt' and pg_get_function_identity_arguments(p.oid)='p_cod_obligation_id uuid, p_parcel_id uuid, p_expected_amount_snapshot numeric, p_received_amount numeric, p_idempotency_key text' and r.rolname='anon' and a.privilege_type='EXECUTE')),'receipt entry remains restricted to authenticated browser role');
select ok((select position('unique' in lower(pg_get_constraintdef(c.oid))) > 0 and position('parcel_id' in pg_get_constraintdef(c.oid)) > 0 from pg_constraint c join pg_class cl on cl.oid=c.conrelid join pg_namespace cn on cn.oid=cl.relnamespace where cn.nspname='public' and cl.relname='cod_receipts' and c.contype='u'),'one COD receipt per parcel is enforced by the database');

select * from finish();
rollback;
