begin;
select plan(10);

select ok((select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_financial_adjustment' and pg_get_function_identity_arguments(p.oid)='p_order_id uuid, p_adjustment_type text, p_delta_amount numeric, p_reason text, p_parcel_id uuid, p_cod_receipt_id uuid, p_idempotency_key text'),'financial adjustment command exists with expected signature');
select ok((select p.prosecdef and p.proconfig @> array['search_path=pg_catalog, public'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_financial_adjustment'),'financial adjustment command uses SECURITY DEFINER and controlled search_path');
select ok((select position('public.app_role() <> ''admin''' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_financial_adjustment'),'financial adjustment command is Admin-only');
select ok((select position('claim_command_idempotency' in pg_get_functiondef(p.oid))>0 and position('complete_command_idempotency' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_financial_adjustment'),'financial adjustment creation is idempotent and retry safe');
select ok((select position('insert into public.financial_adjustments' in pg_get_functiondef(p.oid))>0 and position('performed_by' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_financial_adjustment'),'command creates an append-only financial adjustment row with actor attribution');
select ok((select position('p_parcel_id' in pg_get_functiondef(p.oid))>0 and position('Parcel does not belong to order' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_financial_adjustment'),'optional parcel lineage is validated against the order');
select ok((select position('p_cod_receipt_id' in pg_get_functiondef(p.oid))>0 and position('COD receipt does not belong to order' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_financial_adjustment'),'optional COD receipt lineage is validated against the order');
select ok((select position('FinancialAdjustmentCreated' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_financial_adjustment'),'financial adjustment emits a domain event');
select ok((select position('create_financial_adjustment' in pg_get_functiondef(p.oid))>0 and position('audit_logs' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='create_financial_adjustment'),'financial adjustment is audited');
select ok((select has_function_privilege('public','public.create_financial_adjustment(uuid,text,numeric,text,uuid,uuid,text)','execute')=false and has_function_privilege('authenticated','public.create_financial_adjustment(uuid,text,numeric,text,uuid,uuid,text)','execute')=true),'function access is restricted to authenticated callers');

select * from finish();
rollback;
