begin;
select plan(10);

select ok((select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_cod_financial_reconciliation' and pg_get_function_identity_arguments(p.oid)='p_order_id uuid'),'COD/financial reconciliation function exists with expected signature');
select ok((select p.prosecdef and p.provolatile='s' and p.proconfig @> array['search_path=pg_catalog, public'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_cod_financial_reconciliation'),'reconciliation uses SECURITY DEFINER, STABLE and controlled search_path');
select ok((select position('public.app_role() <> ''admin''' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_cod_financial_reconciliation'),'reconciliation is Admin-only');
select ok((select position('original_amount' in pg_get_functiondef(p.oid))>0 and position('financial_adjustments' in pg_get_functiondef(p.oid))>0 and position('v_effective' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_cod_financial_reconciliation'),'reconciliation derives effective amount from original amount plus financial adjustments');
select ok((select position('cod_obligations' in pg_get_functiondef(p.oid))>0 and position('cod_expected_amount' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_cod_financial_reconciliation'),'reconciliation includes the authoritative COD obligation');
select ok((select position('cod_obligation_allocations' in pg_get_functiondef(p.oid))>0 and position('allocated_expected_amount' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_cod_financial_reconciliation'),'reconciliation includes parcel expected COD allocation totals');
select ok((select position('cod_receipts' in pg_get_functiondef(p.oid))>0 and position('received_amount' in pg_get_functiondef(p.oid))>0 and position('receipt_variance' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_cod_financial_reconciliation'),'reconciliation includes actual receipt totals and receipt variance');
select ok((select position('unresolved_exception_count' in pg_get_functiondef(p.oid))>0 and position('unreceived_allocation_count' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_cod_financial_reconciliation'),'reconciliation exposes unresolved exceptions and missing receipts');
select ok((select position('reconciliation_state := ''Reconciled''' in pg_get_functiondef(p.oid))>0 and position('reconciliation_state := ''Outstanding''' in pg_get_functiondef(p.oid))>0 and position('reconciliation_state := ''Exception''' in pg_get_functiondef(p.oid))>0 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_cod_financial_reconciliation'),'reconciliation distinguishes Reconciled, Outstanding and Exception states');
select ok((select has_function_privilege('public','public.get_cod_financial_reconciliation(uuid)','execute')=false and has_function_privilege('anon','public.get_cod_financial_reconciliation(uuid)','execute')=false and has_function_privilege('authenticated','public.get_cod_financial_reconciliation(uuid)','execute')=true),'reconciliation function access is restricted to authenticated callers');

select * from finish();
rollback;
