-- P11-T183: duplicate COD receipt regression coverage.
begin;

select plan(10);

select ok((select count(*) = 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'record_cod_receipt'),'authoritative COD receipt entry command exists');
select ok((select position('from public.cod_receipts' in pg_get_functiondef(p.oid)) > 0 and position('where parcel_id = p_parcel_id' in pg_get_functiondef(p.oid)) > 0 and position('for update' in pg_get_functiondef(p.oid)) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'record_cod_receipt'),'receipt entry checks the authoritative existing receipt for the parcel');
select ok((select position('if found then' in pg_get_functiondef(p.oid)) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'record_cod_receipt'),'duplicate receipt path is explicitly handled before insert');
select ok((select position('v_receipt.cod_obligation_id' in pg_get_functiondef(p.oid)) > 0 and position('p_cod_obligation_id' in pg_get_functiondef(p.oid)) > 0 and position('v_receipt.expected_amount_snapshot' in pg_get_functiondef(p.oid)) > 0 and position('p_expected_amount_snapshot' in pg_get_functiondef(p.oid)) > 0 and position('v_receipt.received_amount' in pg_get_functiondef(p.oid)) > 0 and position('p_received_amount' in pg_get_functiondef(p.oid)) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'record_cod_receipt'),'duplicate comparison requires the same obligation and receipt amounts');
select ok((select position('complete_command_idempotency' in pg_get_functiondef(p.oid)) > 0 and position('return query select v_receipt.id' in pg_get_functiondef(p.oid)) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'record_cod_receipt'),'an identical duplicate returns the existing receipt and completes idempotency');
select ok((select position('A COD receipt already exists for this parcel' in pg_get_functiondef(p.oid)) > 0 and position('errcode=''23505''' in pg_get_functiondef(p.oid)) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'record_cod_receipt'),'a duplicate with different receipt data is rejected with unique-violation semantics');
select ok((select position('insert into public.cod_receipts' in pg_get_functiondef(p.oid)) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'record_cod_receipt'),'new receipts are inserted only after the duplicate check');
select ok((select c.contype = 'u' and pg_get_constraintdef(c.oid) = 'UNIQUE (parcel_id)' from pg_constraint c join pg_class t on t.oid = c.conrelid join pg_namespace n on n.oid = t.relnamespace where n.nspname = 'public' and t.relname = 'cod_receipts' and c.conname = 'cod_receipts_one_per_parcel_key'),'database uniqueness independently prevents more than one receipt per parcel');
select ok((select position('claim_command_idempotency' in pg_get_functiondef(p.oid)) > 0 and position('not v_claim.is_new' in pg_get_functiondef(p.oid)) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'record_cod_receipt'),'retries using the same idempotency key return the prior command result');
select ok((select position('CodReceiptRecorded' in pg_get_functiondef(p.oid)) > 0 and position('insert into public.audit_logs' in pg_get_functiondef(p.oid)) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'record_cod_receipt'),'the original receipt path retains domain-event and audit evidence without creating a duplicate event path');

select * from finish();
rollback;
