-- P12-T193 static regression coverage for monetary/count reconciliation.
begin;

select plan(12);

select ok((select count(*) = 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reconcile_import_monetary_counts' and pg_get_function_identity_arguments(p.oid) = 'p_batch_id uuid, p_amount_field text, p_expected_row_count integer, p_expected_amount numeric, p_idempotency_key text'),'monetary/count reconciliation command exists with expected signature');
select ok((select p.prosecdef from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reconcile_import_monetary_counts' and pg_get_function_identity_arguments(p.oid) = 'p_batch_id uuid, p_amount_field text, p_expected_row_count integer, p_expected_amount numeric, p_idempotency_key text'),'reconciliation command is SECURITY DEFINER');
select ok((select 'search_path=pg_catalog, public' = any(coalesce(p.proconfig,array[]::text[])) from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reconcile_import_monetary_counts' and pg_get_function_identity_arguments(p.oid) = 'p_batch_id uuid, p_amount_field text, p_expected_row_count integer, p_expected_amount numeric, p_idempotency_key text'),'reconciliation command uses fixed search_path');
select ok((select has_function_privilege('anon','public.reconcile_import_monetary_counts(uuid,text,integer,numeric,text)','EXECUTE') = false),'anon execution revoked');
select ok((select has_function_privilege('authenticated','public.reconcile_import_monetary_counts(uuid,text,integer,numeric,text)','EXECUTE') = true),'authenticated execution retained');
select ok((select position('public.app_role() <> ''admin''' in lower(pg_get_functiondef(p.oid))) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reconcile_import_monetary_counts' and pg_get_function_identity_arguments(p.oid) = 'p_batch_id uuid, p_amount_field text, p_expected_row_count integer, p_expected_amount numeric, p_idempotency_key text'),'reconciliation is Admin-only');
select ok((select position('p_expected_row_count' in lower(pg_get_functiondef(p.oid))) > 0 and position('count_delta' in lower(pg_get_functiondef(p.oid))) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reconcile_import_monetary_counts'),'reconciliation compares source and staged row counts');
select ok((select position('p_expected_amount' in lower(pg_get_functiondef(p.oid))) > 0 and position('actual_amount' in lower(pg_get_functiondef(p.oid))) > 0 and position('amount_delta' in lower(pg_get_functiondef(p.oid))) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reconcile_import_monetary_counts'),'reconciliation compares source and staged monetary totals');
select ok((select position('invalid_amount_count' in lower(pg_get_functiondef(p.oid))) > 0 and position('at most 2 decimal' in lower(pg_get_functiondef(p.oid))) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reconcile_import_monetary_counts'),'reconciliation detects invalid monetary values and precision overflow');
select ok((select position('numeric(12,2)' in lower(pg_get_functiondef(p.oid))) > 0 and position('round(v_actual_amount - p_expected_amount, 2)' in lower(pg_get_functiondef(p.oid))) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reconcile_import_monetary_counts'),'monetary reconciliation uses exact two-decimal numeric arithmetic');
select ok((select position('monetary_count_reconciliation' in lower(pg_get_functiondef(p.oid))) > 0 and position('reconciliation_summary' in lower(pg_get_functiondef(p.oid))) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reconcile_import_monetary_counts'),'reconciliation persists a batch summary without replacing prior staging reconciliation');
select ok((select position('claim_command_idempotency' in lower(pg_get_functiondef(p.oid))) > 0 and position('complete_command_idempotency' in lower(pg_get_functiondef(p.oid))) > 0 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'reconcile_import_monetary_counts'),'reconciliation uses command idempotency');

select * from finish();
rollback;
