// Generated Supabase database types for the v4 application schema.
// Source: ecommerce-operations-staging (mijbpvgxrxjaalimyqgm), synchronized with the repository foundation migration.
// Regenerate with Supabase CLI after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; name: string; email: string; role: string; active: boolean; created_at: string; updated_at: string }; Insert: { id: string; name: string; email: string; role: string; active?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; name?: string; email?: string; role?: string; active?: boolean; created_at?: string; updated_at?: string }; Relationships: [] }
      customers: { Row: { id: string; customer_code: string; name: string; phone: string | null; normalized_phone: string | null; address: string | null; city: string | null; created_at: string; updated_at: string }; Insert: { id?: string; customer_code?: string; name: string; phone?: string | null; normalized_phone?: string | null; address?: string | null; city?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; customer_code?: string; name?: string; phone?: string | null; normalized_phone?: string | null; address?: string | null; city?: string | null; created_at?: string; updated_at?: string }; Relationships: [] }
      shippers: { Row: { id: string; name: string; active: boolean; created_at: string; updated_at: string }; Insert: { id?: string; name: string; active?: boolean; created_at?: string; updated_at?: string }; Update: { id?: string; name?: string; active?: boolean; created_at?: string; updated_at?: string }; Relationships: [] }
      orders: { Row: { id: string; order_number: string; customer_id: string; order_date: string; currency_code: string; original_amount: number; lifecycle_state: string; fulfillment_summary: string | null; notes: string | null; created_by: string; created_at: string; updated_at: string }; Insert: { id?: string; order_number?: string; customer_id: string; order_date?: string; currency_code?: string; original_amount: number; lifecycle_state?: string; fulfillment_summary?: string | null; notes?: string | null; created_by: string; created_at?: string; updated_at?: string }; Update: { id?: string; order_number?: string; customer_id?: string; order_date?: string; currency_code?: string; original_amount?: number; lifecycle_state?: string; fulfillment_summary?: string | null; notes?: string | null; created_by?: string; created_at?: string; updated_at?: string }; Relationships: [{ foreignKeyName: "orders_customer_id_fkey"; columns: ["customer_id"]; isOneToOne: false; referencedRelation: "customers"; referencedColumns: ["id"] }] }
      order_items: { Row: { id: string; order_id: string; line_no: number; description: string; quantity: number; created_at: string; updated_at: string }; Insert: { id?: string; order_id: string; line_no: number; description: string; quantity: number; created_at?: string; updated_at?: string }; Update: { id?: string; order_id?: string; line_no?: number; description?: string; quantity?: number; created_at?: string; updated_at?: string }; Relationships: [{ foreignKeyName: "order_items_order_id_fkey"; columns: ["order_id"]; isOneToOne: false; referencedRelation: "orders"; referencedColumns: ["id"] }] }
      parcels: { Row: { id: string; order_id: string; parcel_number: string; barcode: string; shipper_id: string | null; tracking_id: string | null; state: string; dispatch_at: string | null; rto_at: string | null; created_at: string; updated_at: string }; Insert: { id?: string; order_id: string; parcel_number?: string; barcode: string; shipper_id?: string | null; tracking_id?: string | null; state?: string; dispatch_at?: string | null; rto_at?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; order_id?: string; parcel_number?: string; barcode?: string; shipper_id?: string | null; tracking_id?: string | null; state?: string; dispatch_at?: string | null; rto_at?: string | null; created_at?: string; updated_at?: string }; Relationships: [{ foreignKeyName: "parcels_order_id_fkey"; columns: ["order_id"]; isOneToOne: false; referencedRelation: "orders"; referencedColumns: ["id"] }, { foreignKeyName: "parcels_shipper_id_fkey"; columns: ["shipper_id"]; isOneToOne: false; referencedRelation: "shippers"; referencedColumns: ["id"] }] }
      parcel_items: { Row: { id: string; parcel_id: string; order_item_id: string; quantity: number; allocation_state: string; created_at: string; updated_at: string }; Insert: { id?: string; parcel_id: string; order_item_id: string; quantity: number; allocation_state?: string; created_at?: string; updated_at?: string }; Update: { id?: string; parcel_id?: string; order_item_id?: string; quantity?: number; allocation_state?: string; created_at?: string; updated_at?: string }; Relationships: [{ foreignKeyName: "parcel_items_order_item_id_fkey"; columns: ["order_item_id"]; isOneToOne: false; referencedRelation: "order_items"; referencedColumns: ["id"] }, { foreignKeyName: "parcel_items_parcel_id_fkey"; columns: ["parcel_id"]; isOneToOne: false; referencedRelation: "parcels"; referencedColumns: ["id"] }] }
      delivery_outcomes: { Row: { id: string; parcel_id: string; outcome: string; note: string | null; occurred_at: string; performed_by: string }; Insert: { id?: string; parcel_id: string; outcome: string; note?: string | null; occurred_at?: string; performed_by: string }; Update: { id?: string; parcel_id?: string; outcome?: string; note?: string | null; occurred_at?: string; performed_by?: string }; Relationships: [{ foreignKeyName: "delivery_outcomes_parcel_id_fkey"; columns: ["parcel_id"]; isOneToOne: false; referencedRelation: "parcels"; referencedColumns: ["id"] }] }
      cod_obligations: { Row: { id: string; order_id: string; expected_amount: number; state: string; created_at: string; closed_at: string | null; closed_by: string | null }; Insert: { id?: string; order_id: string; expected_amount: number; state?: string; created_at?: string; closed_at?: string | null; closed_by?: string | null }; Update: { id?: string; order_id?: string; expected_amount?: number; state?: string; created_at?: string; closed_at?: string | null; closed_by?: string | null }; Relationships: [{ foreignKeyName: "cod_obligations_order_id_fkey"; columns: ["order_id"]; isOneToOne: true; referencedRelation: "orders"; referencedColumns: ["id"] }] }
      cod_obligation_allocations: { Row: { id: string; cod_obligation_id: string; parcel_id: string; expected_amount: number; created_at: string }; Insert: { id?: string; cod_obligation_id: string; parcel_id: string; expected_amount: number; created_at?: string }; Update: { id?: string; cod_obligation_id?: string; parcel_id?: string; expected_amount?: number; created_at?: string }; Relationships: [{ foreignKeyName: "cod_obligation_allocations_cod_obligation_id_fkey"; columns: ["cod_obligation_id"]; isOneToOne: false; referencedRelation: "cod_obligations"; referencedColumns: ["id"] }, { foreignKeyName: "cod_obligation_allocations_parcel_id_fkey"; columns: ["parcel_id"]; isOneToOne: false; referencedRelation: "parcels"; referencedColumns: ["id"] }] }
      cod_receipts: { Row: { id: string; cod_obligation_id: string; parcel_id: string; expected_amount_snapshot: number; received_amount: number; state: string; received_at: string; received_by: string }; Insert: { id?: string; cod_obligation_id: string; parcel_id: string; expected_amount_snapshot: number; received_amount: number; state: string; received_at?: string; received_by: string }; Update: { id?: string; cod_obligation_id?: string; parcel_id?: string; expected_amount_snapshot?: number; received_amount?: number; state?: string; received_at?: string; received_by?: string }; Relationships: [{ foreignKeyName: "cod_receipts_cod_obligation_id_fkey"; columns: ["cod_obligation_id"]; isOneToOne: false; referencedRelation: "cod_obligations"; referencedColumns: ["id"] }, { foreignKeyName: "cod_receipts_parcel_id_fkey"; columns: ["parcel_id"]; isOneToOne: true; referencedRelation: "parcels"; referencedColumns: ["id"] }] }
      financial_adjustments: { Row: { id: string; order_id: string; adjustment_type: string; delta_amount: number; reason: string; performed_by: string; performed_at: string; parcel_id: string | null; cod_receipt_id: string | null }; Insert: { id?: string; order_id: string; adjustment_type: string; delta_amount: number; reason: string; performed_by: string; performed_at?: string; parcel_id?: string | null; cod_receipt_id?: string | null }; Update: { id?: string; order_id?: string; adjustment_type?: string; delta_amount?: number; reason?: string; performed_by?: string; performed_at?: string; parcel_id?: string | null; cod_receipt_id?: string | null }; Relationships: [{ foreignKeyName: "financial_adjustments_cod_receipt_id_fkey"; columns: ["cod_receipt_id"]; isOneToOne: false; referencedRelation: "cod_receipts"; referencedColumns: ["id"] }, { foreignKeyName: "financial_adjustments_order_id_fkey"; columns: ["order_id"]; isOneToOne: false; referencedRelation: "orders"; referencedColumns: ["id"] }, { foreignKeyName: "financial_adjustments_parcel_id_fkey"; columns: ["parcel_id"]; isOneToOne: false; referencedRelation: "parcels"; referencedColumns: ["id"] }] }
      invoice_records: { Row: { id: string; order_id: string; invoice_number: string; template_version: string; generated_at: string; generated_by: string; print_count: number }; Insert: { id?: string; order_id: string; invoice_number: string; template_version: string; generated_at?: string; generated_by: string; print_count?: number }; Update: { id?: string; order_id?: string; invoice_number?: string; template_version?: string; generated_at?: string; generated_by?: string; print_count?: number }; Relationships: [{ foreignKeyName: "invoice_records_order_id_fkey"; columns: ["order_id"]; isOneToOne: false; referencedRelation: "orders"; referencedColumns: ["id"] }] }
      order_events: { Row: { id: string; order_id: string; parcel_id: string | null; event_type: string; event_time: string; performed_by: string; notes: string | null; metadata: Json }; Insert: { id?: string; order_id: string; parcel_id?: string | null; event_type: string; event_time?: string; performed_by: string; notes?: string | null; metadata?: Json }; Update: { id?: string; order_id?: string; parcel_id?: string | null; event_type?: string; event_time?: string; performed_by?: string; notes?: string | null; metadata?: Json }; Relationships: [{ foreignKeyName: "order_events_order_id_fkey"; columns: ["order_id"]; isOneToOne: false; referencedRelation: "orders"; referencedColumns: ["id"] }, { foreignKeyName: "order_events_parcel_id_fkey"; columns: ["parcel_id"]; isOneToOne: false; referencedRelation: "parcels"; referencedColumns: ["id"] }] }
      audit_logs: { Row: { id: string; actor: string | null; action: string; entity_type: string; entity_id: string | null; before_data: Json | null; after_data: Json | null; request_id: string | null; occurred_at: string }; Insert: { id?: string; actor?: string | null; action: string; entity_type: string; entity_id?: string | null; before_data?: Json | null; after_data?: Json | null; request_id?: string | null; occurred_at?: string }; Update: { id?: string; actor?: string | null; action?: string; entity_type?: string; entity_id?: string | null; before_data?: Json | null; after_data?: Json | null; request_id?: string | null; occurred_at?: string }; Relationships: [] }
      import_batches: { Row: { id: string; source_system: string; source_file: string; initiated_by: string; status: string; started_at: string | null; completed_at: string | null; reconciliation_summary: Json | null }; Insert: { id?: string; source_system: string; source_file: string; initiated_by: string; status?: string; started_at?: string | null; completed_at?: string | null; reconciliation_summary?: Json | null }; Update: { id?: string; source_system?: string; source_file?: string; initiated_by?: string; status?: string; started_at?: string | null; completed_at?: string | null; reconciliation_summary?: Json | null }; Relationships: [] }
      import_rows: { Row: { id: string; batch_id: string; source_row_number: number; source_record_id: string | null; raw_data: Json; normalized_data: Json | null; status: string; error: string | null }; Insert: { id?: string; batch_id: string; source_row_number: number; source_record_id?: string | null; raw_data: Json; normalized_data?: Json | null; status?: string; error?: string | null }; Update: { id?: string; batch_id?: string; source_row_number?: number; source_record_id?: string | null; raw_data?: Json; normalized_data?: Json | null; status?: string; error?: string | null }; Relationships: [{ foreignKeyName: "import_rows_batch_id_fkey"; columns: ["batch_id"]; isOneToOne: false; referencedRelation: "import_batches"; referencedColumns: ["id"] }] }
    }
    Views: { [_ in never]: never }
    Functions: {
      app_role: { Args: never; Returns: string }
      resolve_customer_by_phone: { Args: { p_phone: string }; Returns: { customer_id: string; customer_code: string; name: string; phone: string | null; normalized_phone: string | null; address: string | null; city: string | null }[] }
      create_order: { Args: { p_customer_name: string; p_phone: string; p_address: string; p_city: string; p_original_amount: number; p_items: Json; p_notes?: string | null }; Returns: { order_id: string; order_number: string; customer_id: string }[] }
      confirm_order: { Args: { p_order_id: string }; Returns: { order_id: string; order_number: string; lifecycle_state: string }[] }
      cancel_order: { Args: { p_order_id: string }; Returns: { order_id: string; order_number: string; lifecycle_state: string }[] }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]
export type CompositeTypes<T extends keyof Database['public']['CompositeTypes']> = Database['public']['CompositeTypes'][T]

export const Constants = { public: { Enums: {} } } as const
